export const socials = [
	{
		id: 1,
		icon: '/icons/github.svg',
		href: 'https://github.com/nklmantey',
	},
	{
		id: 2,
		icon: '/icons/x.svg',
		href: 'https://x.com/nklmantey',
	},
	{
		id: 3,
		icon: '/icons/mail.svg',
		href: 'mailto:nklmantey@gmail.com',
	},
]

export const projects = [
	{
		id: 0,
		keyId: 'glide',
		projectName: 'Glide',
		year: '2025',
		description: 'Tauri and Rust-based workspace manager for seamless environment switching.',
		image: '/projects/glide.png',
		href: 'https://github.com/nklmantey/glide',
		tags: ['Personal'],
	},
	{
		id: 1,
		keyId: 'plunk',
		projectName: 'Plunk',
		year: '2025',
		image: '/projects/plunk.png',
		href: 'https://www.useplunk.com/',
		description: 'Open-source email platform unifying marketing and transactional emails ',
		tags: ['Open Source'],
	},
	{
		id: 2,
		keyId: 'twenty',
		projectName: 'Twenty',
		year: '2024',
		image: '/projects/twenty.png',
		href: 'https://twenty.com/',
		description: 'Open-source CRM platform enhancing customer relationship management.',
		tags: ['Open Source'],
	},
	{
		id: 3,
		keyId: 'bigcapital',
		projectName: 'Bigcapital',
		year: '2024',
		image: '/projects/bigcapital.png',
		href: 'https://bigcapital.app/',
		description: 'Modern core accounting software automating business finances.',
		tags: ['Open Source'],
	},
	{
		id: 4,
		keyId: 'backpack',
		projectName: 'Backpack',
		year: '2024',
		image: '/projects/backpack.png',
		href: 'https://backpack.app/',
		description: 'Comprehensive crypto app supporting Solana, Ethereum, and Bitcoin.',
		tags: ['Open Source'],
	},
	{
		id: 5,
		keyId: 'tapngo',
		projectName: "Tap n' Go",
		year: '2023',
		description: "Ghana's unified digital payment system streamlining public transport fares.",
		image: '/projects/tapngo.png',
		href: 'https://tapngogh.com/',
		tags: ['Work'],
	},
	{
		id: 6,
		keyId: 'eazyed',
		projectName: 'EazyEd',
		year: '2023',
		image: '/projects/eazyed.png',
		href: 'https://beta.eazyed.org/',
		description: 'Engaging video lessons and quizzes aligned with, and for the Ghanaian curriculum.',
		tags: ['Work', 'Beta'],
	},
]
